### ISSUE TITLE
Please support JUMP.

### ISSUE THREAD

**Issue by dragon2611** [voxpupuli/puppet-ferm#61]
As Title, it looks like you can define custom chains, but I don't see any option to configure the criteria/Jump from the default chain to the custom one.

e.g

> ferm::rules:
>   'jump_trusted':
>    chain: 'INPUT'
>    policy: 'JUMP'
>    saddr: "%{alias('Trusted')}"
>    jumpto: 'Trusted-Hosts' 
>   'trusted_ssh':
>    chain: 'Trusted-Hosts'
>    policy: 'ACCEPT'
>    proto: 'tcp'
>    dport: '22'

**Comment by foxxx0** [comment]
Hey, thanks for the bug report.
Work on this already ongoing in the `multi-table-support` branch and currently undergoing the last validations steps along with some further testing.
See: https://github.com/voxpupuli/puppet-ferm/pull/58
